name: CI
on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main
      - renovate/*
  workflow_call:
    inputs:
      version:
        description: The version to set in the package.json files
        default: "0.0.0"
        required: false
        type: string

defaults:
  run:
    shell: pwsh

env:
  NODE_VERSION: 21

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run EsLint
        run: npx nx run-many --target lint

      - name: Run Prettier
        run: npx prettier --check .

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx nx run-many --target build --configuration production

      - name: Log Version
        run: Write-Host ${{ inputs.version }}

      - name: Set Version
        if: inputs.version != ''
        run: npx nx run-many --target version --args="--version=${{ inputs.version }}"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          retention-days: 1

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npx nx run-many --target test --configuration ci

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage

  e2e:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 18
          - 20
          - 21
        test:
          - name: higher-patch-version
            result: latest
          - name: higher-minor-version
            result: latest
          - name: higher-major-version
            result: latest
          - name: higher-patch-version-than-v1
            result: latest-1
          - name: higher-minor-version-than-v1
            result: latest-1
          - name: lower-major-version-than-all
            result: latest-0
          - name: does-not-exist
            result: latest
          - name: invalid-path
            result: ""

    name: e2e-${{ matrix.test.name }} using Node ${{ matrix.node }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: ./
        continue-on-error: true
        id: subject
        with:
          package-json: "./e2e/${{ matrix.test.name }}/package.json"

      - if: always()
        shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latest-tag }}" -eq "${{ matrix.test.result }}" ? 0 : 1)'
